package io.github.chutian0610.sqlparser.token

/** KeyWords with UpperCase Text.
  *
  *   1. a list of KeyWord used in sql. 2. some of these can be parsed as identifiers according to
  *      parser.
  * @param text
  *   keyword string value
  */
enum KeyWordEnum(val text: String):
  case ABORT                             extends KeyWordEnum("ABORT")
  case  ABS                              extends KeyWordEnum("ABS")
  case  ABSENT                           extends KeyWordEnum("ABSENT")
  case  ABSOLUTE                         extends KeyWordEnum("ABSOLUTE")
  case  ACCESS                           extends KeyWordEnum("ACCESS")
  case  ACCOUNT                          extends KeyWordEnum("ACCOUNT")
  case  ACTION                           extends KeyWordEnum("ACTION")
  case  ADD                              extends KeyWordEnum("ADD")
  case  ADMIN                            extends KeyWordEnum("ADMIN")
  case  AFTER                            extends KeyWordEnum("AFTER")
  case  AGAINST                          extends KeyWordEnum("AGAINST")
  case  AGGREGATE                        extends KeyWordEnum("AGGREGATE")
  case  AGGREGATION                      extends KeyWordEnum("AGGREGATION")
  case  ALERT                            extends KeyWordEnum("ALERT")
  case  ALGORITHM                        extends KeyWordEnum("ALGORITHM")
  case  ALIAS                            extends KeyWordEnum("ALIAS")
  case  ALL                              extends KeyWordEnum("ALL")
  case  ALLOCATE                         extends KeyWordEnum("ALLOCATE")
  case  ALTER                            extends KeyWordEnum("ALTER")
  case  ALWAYS                           extends KeyWordEnum("ALWAYS")
  case  ANALYZE                          extends KeyWordEnum("ANALYZE")
  case  AND                              extends KeyWordEnum("AND")
  case  ANTI                             extends KeyWordEnum("ANTI")
  case  ANY                              extends KeyWordEnum("ANY")
  case  APPLICATION                      extends KeyWordEnum("APPLICATION")
  case  APPLY                            extends KeyWordEnum("APPLY")
  case  APPLYBUDGET                      extends KeyWordEnum("APPLYBUDGET")
  case  ARCHIVE                          extends KeyWordEnum("ARCHIVE")
  case  ARE                              extends KeyWordEnum("ARE")
  case  ARRAY                            extends KeyWordEnum("ARRAY")
  case  ARRAY_MAX_CARDINALITY            extends KeyWordEnum("ARRAY_MAX_CARDINALITY")
  case  AS                               extends KeyWordEnum("AS")
  case  ASC                              extends KeyWordEnum("ASC")
  case  ASENSITIVE                       extends KeyWordEnum("ASENSITIVE")
  case  ASOF                             extends KeyWordEnum("ASOF")
  case  ASSERT                           extends KeyWordEnum("ASSERT")
  case  ASYMMETRIC                       extends KeyWordEnum("ASYMMETRIC")
  case  AT                               extends KeyWordEnum("AT")
  case  ATOMIC                           extends KeyWordEnum("ATOMIC")
  case  ATTACH                           extends KeyWordEnum("ATTACH")
  case  AUDIT                            extends KeyWordEnum("AUDIT")
  case  AUTHENTICATION                   extends KeyWordEnum("AUTHENTICATION")
  case  AUTHORIZATION                    extends KeyWordEnum("AUTHORIZATION")
  case  AUTO                             extends KeyWordEnum("AUTO")
  case  AUTOEXTEND_SIZE                  extends KeyWordEnum("AUTOEXTEND_SIZE")
  case  AUTOINCREMENT                    extends KeyWordEnum("AUTOINCREMENT")
  case  AUTO_INCREMENT                   extends KeyWordEnum("AUTO_INCREMENT")
  case  AVG                              extends KeyWordEnum("AVG")
  case  AVG_ROW_LENGTH                   extends KeyWordEnum("AVG_ROW_LENGTH")
  case  AVRO                             extends KeyWordEnum("AVRO")
  case  BACKWARD                         extends KeyWordEnum("BACKWARD")
  case  BASE64                           extends KeyWordEnum("BASE64")
  case  BASE_LOCATION                    extends KeyWordEnum("BASE_LOCATION")
  case  BEFORE                           extends KeyWordEnum("BEFORE")
  case  BEGIN                            extends KeyWordEnum("BEGIN")
  case  BEGIN_FRAME                      extends KeyWordEnum("BEGIN_FRAME")
  case  BEGIN_PARTITION                  extends KeyWordEnum("BEGIN_PARTITION")
  case  BERNOULLI                        extends KeyWordEnum("BERNOULLI")
  case  BETWEEN                          extends KeyWordEnum("BETWEEN")
  case  BIGDECIMAL                       extends KeyWordEnum("BIGDECIMAL")
  case  BIGINT                           extends KeyWordEnum("BIGINT")
  case  BIGNUMERIC                       extends KeyWordEnum("BIGNUMERIC")
  case  BINARY                           extends KeyWordEnum("BINARY")
  case  BIND                             extends KeyWordEnum("BIND")
  case  BINDING                          extends KeyWordEnum("BINDING")
  case  BIT                              extends KeyWordEnum("BIT")
  case  BLOB                             extends KeyWordEnum("BLOB")
  case  BLOCK                            extends KeyWordEnum("BLOCK")
  case  BLOOM                            extends KeyWordEnum("BLOOM")
  case  BLOOMFILTER                      extends KeyWordEnum("BLOOMFILTER")
  case  BOOL                             extends KeyWordEnum("BOOL")
  case  BOOLEAN                          extends KeyWordEnum("BOOLEAN")
  case  BOTH                             extends KeyWordEnum("BOTH")
  case  BOX                              extends KeyWordEnum("BOX")
  case  BRIN                             extends KeyWordEnum("BRIN")
  case  BROWSE                           extends KeyWordEnum("BROWSE")
  case  BTREE                            extends KeyWordEnum("BTREE")
  case  BUCKET                           extends KeyWordEnum("BUCKET")
  case  BUCKETS                          extends KeyWordEnum("BUCKETS")
  case  BY                               extends KeyWordEnum("BY")
  case  BYPASSRLS                        extends KeyWordEnum("BYPASSRLS")
  case  BYTEA                            extends KeyWordEnum("BYTEA")
  case  BYTES                            extends KeyWordEnum("BYTES")
  case  CACHE                            extends KeyWordEnum("CACHE")
  case  CALL                             extends KeyWordEnum("CALL")
  case  CALLED                           extends KeyWordEnum("CALLED")
  case  CARDINALITY                      extends KeyWordEnum("CARDINALITY")
  case  CASCADE                          extends KeyWordEnum("CASCADE")
  case  CASCADED                         extends KeyWordEnum("CASCADED")
  case  CASE                             extends KeyWordEnum("CASE")
  case  CASES                            extends KeyWordEnum("CASES")
  case  CAST                             extends KeyWordEnum("CAST")
  case  CATALOG                          extends KeyWordEnum("CATALOG")
  case  CATALOG_SYNC                     extends KeyWordEnum("CATALOG_SYNC")
  case  CATCH                            extends KeyWordEnum("CATCH")
  case  CEIL                             extends KeyWordEnum("CEIL")
  case  CEILING                          extends KeyWordEnum("CEILING")
  case  CENTURY                          extends KeyWordEnum("CENTURY")
  case  CHAIN                            extends KeyWordEnum("CHAIN")
  case  CHANGE                           extends KeyWordEnum("CHANGE")
  case  CHANGE_TRACKING                  extends KeyWordEnum("CHANGE_TRACKING")
  case  CHANNEL                          extends KeyWordEnum("CHANNEL")
  case  CHAR                             extends KeyWordEnum("CHAR")
  case  CHARACTER                        extends KeyWordEnum("CHARACTER")
  case  CHARACTERISTICS                  extends KeyWordEnum("CHARACTERISTICS")
  case  CHARACTERS                       extends KeyWordEnum("CHARACTERS")
  case  CHARACTER_LENGTH                 extends KeyWordEnum("CHARACTER_LENGTH")
  case  CHARSET                          extends KeyWordEnum("CHARSET")
  case  CHAR_LENGTH                      extends KeyWordEnum("CHAR_LENGTH")
  case  CHECK                            extends KeyWordEnum("CHECK")
  case  CHECKSUM                         extends KeyWordEnum("CHECKSUM")
  case  CIRCLE                           extends KeyWordEnum("CIRCLE")
  case  CLEAR                            extends KeyWordEnum("CLEAR")
  case  CLOB                             extends KeyWordEnum("CLOB")
  case  CLONE                            extends KeyWordEnum("CLONE")
  case  CLOSE                            extends KeyWordEnum("CLOSE")
  case  CLUSTER                          extends KeyWordEnum("CLUSTER")
  case  CLUSTERED                        extends KeyWordEnum("CLUSTERED")
  case  CLUSTERING                       extends KeyWordEnum("CLUSTERING")
  case  COALESCE                         extends KeyWordEnum("COALESCE")
  case  COLLATE                          extends KeyWordEnum("COLLATE")
  case  COLLATION                        extends KeyWordEnum("COLLATION")
  case  COLLECT                          extends KeyWordEnum("COLLECT")
  case  COLLECTION                       extends KeyWordEnum("COLLECTION")
  case  COLUMN                           extends KeyWordEnum("COLUMN")
  case  COLUMNS                          extends KeyWordEnum("COLUMNS")
  case  COLUMNSTORE                      extends KeyWordEnum("COLUMNSTORE")
  case  COMMENT                          extends KeyWordEnum("COMMENT")
  case  COMMIT                           extends KeyWordEnum("COMMIT")
  case  COMMITTED                        extends KeyWordEnum("COMMITTED")
  case  COMPATIBLE                       extends KeyWordEnum("COMPATIBLE")
  case  COMPRESSION                      extends KeyWordEnum("COMPRESSION")
  case  COMPUTE                          extends KeyWordEnum("COMPUTE")
  case  CONCURRENTLY                     extends KeyWordEnum("CONCURRENTLY")
  case  CONDITION                        extends KeyWordEnum("CONDITION")
  case  CONFLICT                         extends KeyWordEnum("CONFLICT")
  case  CONNECT                          extends KeyWordEnum("CONNECT")
  case  CONNECTION                       extends KeyWordEnum("CONNECTION")
  case  CONNECTOR                        extends KeyWordEnum("CONNECTOR")
  case  CONNECT_BY_ROOT                  extends KeyWordEnum("CONNECT_BY_ROOT")
  case  CONSTRAINT                       extends KeyWordEnum("CONSTRAINT")
  case  CONTAINS                         extends KeyWordEnum("CONTAINS")
  case  CONTINUE                         extends KeyWordEnum("CONTINUE")
  case  CONVERT                          extends KeyWordEnum("CONVERT")
  case  COPY                             extends KeyWordEnum("COPY")
  case  COPY_OPTIONS                     extends KeyWordEnum("COPY_OPTIONS")
  case  CORR                             extends KeyWordEnum("CORR")
  case  CORRESPONDING                    extends KeyWordEnum("CORRESPONDING")
  case  COUNT                            extends KeyWordEnum("COUNT")
  case  COVAR_POP                        extends KeyWordEnum("COVAR_POP")
  case  COVAR_SAMP                       extends KeyWordEnum("COVAR_SAMP")
  case  CREATE                           extends KeyWordEnum("CREATE")
  case  CREATEDB                         extends KeyWordEnum("CREATEDB")
  case  CREATEROLE                       extends KeyWordEnum("CREATEROLE")
  case  CREDENTIALS                      extends KeyWordEnum("CREDENTIALS")
  case  CROSS                            extends KeyWordEnum("CROSS")
  case  CSV                              extends KeyWordEnum("CSV")
  case  CUBE                             extends KeyWordEnum("CUBE")
  case  CUME_DIST                        extends KeyWordEnum("CUME_DIST")
  case  CURRENT                          extends KeyWordEnum("CURRENT")
  case  CURRENT_CATALOG                  extends KeyWordEnum("CURRENT_CATALOG")
  case  CURRENT_DATE                     extends KeyWordEnum("CURRENT_DATE")
  case  CURRENT_DEFAULT_TRANSFORM_GROUP  extends KeyWordEnum("CURRENT_DEFAULT_TRANSFORM_GROUP")
  case  CURRENT_PATH                     extends KeyWordEnum("CURRENT_PATH")
  case  CURRENT_ROLE                     extends KeyWordEnum("CURRENT_ROLE")
  case  CURRENT_ROW                      extends KeyWordEnum("CURRENT_ROW")
  case  CURRENT_SCHEMA                   extends KeyWordEnum("CURRENT_SCHEMA")
  case  CURRENT_TIME                     extends KeyWordEnum("CURRENT_TIME")
  case  CURRENT_TIMESTAMP                extends KeyWordEnum("CURRENT_TIMESTAMP")
  case  CURRENT_TRANSFORM_GROUP_FOR_TYPE extends KeyWordEnum("CURRENT_TRANSFORM_GROUP_FOR_TYPE")
  case  CURRENT_USER                     extends KeyWordEnum("CURRENT_USER")
  case  CURSOR                           extends KeyWordEnum("CURSOR")
  case  CYCLE                            extends KeyWordEnum("CYCLE")
  case  DATA                             extends KeyWordEnum("DATA")
  case  DATABASE                         extends KeyWordEnum("DATABASE")
  case  DATABASES                        extends KeyWordEnum("DATABASES")
  case  DATA_RETENTION_TIME_IN_DAYS      extends KeyWordEnum("DATA_RETENTION_TIME_IN_DAYS")
  case  DATE                             extends KeyWordEnum("DATE")
  case  DATE32                           extends KeyWordEnum("DATE32")
  case  DATETIME                         extends KeyWordEnum("DATETIME")
  case  DATETIME64                       extends KeyWordEnum("DATETIME64")
  case  DAY                              extends KeyWordEnum("DAY")
  case  DAYOFWEEK                        extends KeyWordEnum("DAYOFWEEK")
  case  DAYOFYEAR                        extends KeyWordEnum("DAYOFYEAR")
  case  DAYS                             extends KeyWordEnum("DAYS")
  case  DCPROPERTIES                     extends KeyWordEnum("DCPROPERTIES")
  case  DEALLOCATE                       extends KeyWordEnum("DEALLOCATE")
  case  DEC                              extends KeyWordEnum("DEC")
  case  DECADE                           extends KeyWordEnum("DECADE")
  case  DECIMAL                          extends KeyWordEnum("DECIMAL")
  case  DECLARE                          extends KeyWordEnum("DECLARE")
  case  DEDUPLICATE                      extends KeyWordEnum("DEDUPLICATE")
  case  DEFAULT                          extends KeyWordEnum("DEFAULT")
  case  DEFAULT_DDL_COLLATION            extends KeyWordEnum("DEFAULT_DDL_COLLATION")
  case  DEFERRABLE                       extends KeyWordEnum("DEFERRABLE")
  case  DEFERRED                         extends KeyWordEnum("DEFERRED")
  case  DEFINE                           extends KeyWordEnum("DEFINE")
  case  DEFINED                          extends KeyWordEnum("DEFINED")
  case  DEFINER                          extends KeyWordEnum("DEFINER")
  case  DELAYED                          extends KeyWordEnum("DELAYED")
  case  DELAY_KEY_WRITE                  extends KeyWordEnum("DELAY_KEY_WRITE")
  case  DELETE                           extends KeyWordEnum("DELETE")
  case  DELIMITED                        extends KeyWordEnum("DELIMITED")
  case  DELIMITER                        extends KeyWordEnum("DELIMITER")
  case  DELTA                            extends KeyWordEnum("DELTA")
  case  DENSE_RANK                       extends KeyWordEnum("DENSE_RANK")
  case  DENY                             extends KeyWordEnum("DENY")
  case  DEREF                            extends KeyWordEnum("DEREF")
  case  DESC                             extends KeyWordEnum("DESC")
  case  DESCRIBE                         extends KeyWordEnum("DESCRIBE")
  case  DETACH                           extends KeyWordEnum("DETACH")
  case  DETAIL                           extends KeyWordEnum("DETAIL")
  case  DETERMINISTIC                    extends KeyWordEnum("DETERMINISTIC")
  case  DIRECTORY                        extends KeyWordEnum("DIRECTORY")
  case  DISABLE                          extends KeyWordEnum("DISABLE")
  case  DISCARD                          extends KeyWordEnum("DISCARD")
  case  DISCONNECT                       extends KeyWordEnum("DISCONNECT")
  case  DISTINCT                         extends KeyWordEnum("DISTINCT")
  case  DISTRIBUTE                       extends KeyWordEnum("DISTRIBUTE")
  case  DIV                              extends KeyWordEnum("DIV")
  case  DO                               extends KeyWordEnum("DO")
  case  DOMAIN                           extends KeyWordEnum("DOMAIN")
  case  DOUBLE                           extends KeyWordEnum("DOUBLE")
  case  DOW                              extends KeyWordEnum("DOW")
  case  DOY                              extends KeyWordEnum("DOY")
  case  DROP                             extends KeyWordEnum("DROP")
  case  DRY                              extends KeyWordEnum("DRY")
  case  DUPLICATE                        extends KeyWordEnum("DUPLICATE")
  case  DYNAMIC                          extends KeyWordEnum("DYNAMIC")
  case  EACH                             extends KeyWordEnum("EACH")
  case  ELEMENT                          extends KeyWordEnum("ELEMENT")
  case  ELEMENTS                         extends KeyWordEnum("ELEMENTS")
  case  ELSE                             extends KeyWordEnum("ELSE")
  case  ELSEIF                           extends KeyWordEnum("ELSEIF")
  case  EMPTY                            extends KeyWordEnum("EMPTY")
  case  ENABLE                           extends KeyWordEnum("ENABLE")
  case  ENABLE_SCHEMA_EVOLUTION          extends KeyWordEnum("ENABLE_SCHEMA_EVOLUTION")
  case  ENCODING                         extends KeyWordEnum("ENCODING")
  case  ENCRYPTION                       extends KeyWordEnum("ENCRYPTION")
  case  END                              extends KeyWordEnum("END")
  case  END_EXEC                         extends KeyWordEnum("END-EXEC")
  case  ENDPOINT                         extends KeyWordEnum("ENDPOINT")
  case  END_FRAME                        extends KeyWordEnum("END_FRAME")
  case  END_PARTITION                    extends KeyWordEnum("END_PARTITION")
  case  ENFORCED                         extends KeyWordEnum("ENFORCED")
  case  ENGINE                           extends KeyWordEnum("ENGINE")
  case  ENGINE_ATTRIBUTE                 extends KeyWordEnum("ENGINE_ATTRIBUTE")
  case  ENUM                             extends KeyWordEnum("ENUM")
  case  ENUM16                           extends KeyWordEnum("ENUM16")
  case  ENUM8                            extends KeyWordEnum("ENUM8")
  case  EPHEMERAL                        extends KeyWordEnum("EPHEMERAL")
  case  EPOCH                            extends KeyWordEnum("EPOCH")
  case  EQUALS                           extends KeyWordEnum("EQUALS")
  case  ERROR                            extends KeyWordEnum("ERROR")
  case  ESCAPE                           extends KeyWordEnum("ESCAPE")
  case  ESCAPED                          extends KeyWordEnum("ESCAPED")
  case  ESTIMATE                         extends KeyWordEnum("ESTIMATE")
  case  EVENT                            extends KeyWordEnum("EVENT")
  case  EVERY                            extends KeyWordEnum("EVERY")
  case  EVOLVE                           extends KeyWordEnum("EVOLVE")
  case  EXCEPT                           extends KeyWordEnum("EXCEPT")
  case  EXCEPTION                        extends KeyWordEnum("EXCEPTION")
  case  EXCHANGE                         extends KeyWordEnum("EXCHANGE")
  case  EXCLUDE                          extends KeyWordEnum("EXCLUDE")
  case  EXCLUSIVE                        extends KeyWordEnum("EXCLUSIVE")
  case  EXEC                             extends KeyWordEnum("EXEC")
  case  EXECUTE                          extends KeyWordEnum("EXECUTE")
  case  EXECUTION                        extends KeyWordEnum("EXECUTION")
  case  EXISTS                           extends KeyWordEnum("EXISTS")
  case  EXP                              extends KeyWordEnum("EXP")
  case  EXPANSION                        extends KeyWordEnum("EXPANSION")
  case  EXPLAIN                          extends KeyWordEnum("EXPLAIN")
  case  EXPLICIT                         extends KeyWordEnum("EXPLICIT")
  case  EXPORT                           extends KeyWordEnum("EXPORT")
  case  EXTEND                           extends KeyWordEnum("EXTEND")
  case  EXTENDED                         extends KeyWordEnum("EXTENDED")
  case  EXTENSION                        extends KeyWordEnum("EXTENSION")
  case  EXTERNAL                         extends KeyWordEnum("EXTERNAL")
  case  EXTERNAL_VOLUME                  extends KeyWordEnum("EXTERNAL_VOLUME")
  case  EXTRACT                          extends KeyWordEnum("EXTRACT")
  case  FAIL                             extends KeyWordEnum("FAIL")
  case  FAILOVER                         extends KeyWordEnum("FAILOVER")
  case  FALSE                            extends KeyWordEnum("FALSE")
  case  FETCH                            extends KeyWordEnum("FETCH")
  case  FIELDS                           extends KeyWordEnum("FIELDS")
  case  FILE                             extends KeyWordEnum("FILE")
  case  FILES                            extends KeyWordEnum("FILES")
  case  FILE_FORMAT                      extends KeyWordEnum("FILE_FORMAT")
  case  FILL                             extends KeyWordEnum("FILL")
  case  FILTER                           extends KeyWordEnum("FILTER")
  case  FINAL                            extends KeyWordEnum("FINAL")
  case  FIRST                            extends KeyWordEnum("FIRST")
  case  FIRST_VALUE                      extends KeyWordEnum("FIRST_VALUE")
  case  FIXEDSTRING                      extends KeyWordEnum("FIXEDSTRING")
  case  FLOAT                            extends KeyWordEnum("FLOAT")
  case  FLOAT32                          extends KeyWordEnum("FLOAT32")
  case  FLOAT4                           extends KeyWordEnum("FLOAT4")
  case  FLOAT64                          extends KeyWordEnum("FLOAT64")
  case  FLOAT8                           extends KeyWordEnum("FLOAT8")
  case  FLOOR                            extends KeyWordEnum("FLOOR")
  case  FLUSH                            extends KeyWordEnum("FLUSH")
  case  FN                               extends KeyWordEnum("FN")
  case  FOLLOWING                        extends KeyWordEnum("FOLLOWING")
  case  FOR                              extends KeyWordEnum("FOR")
  case  FORCE                            extends KeyWordEnum("FORCE")
  case  FORCE_NOT_NULL                   extends KeyWordEnum("FORCE_NOT_NULL")
  case  FORCE_NULL                       extends KeyWordEnum("FORCE_NULL")
  case  FORCE_QUOTE                      extends KeyWordEnum("FORCE_QUOTE")
  case  FOREIGN                          extends KeyWordEnum("FOREIGN")
  case  FORMAT                           extends KeyWordEnum("FORMAT")
  case  FORMATTED                        extends KeyWordEnum("FORMATTED")
  case  FORWARD                          extends KeyWordEnum("FORWARD")
  case  FRAME_ROW                        extends KeyWordEnum("FRAME_ROW")
  case  FREE                             extends KeyWordEnum("FREE")
  case  FREEZE                           extends KeyWordEnum("FREEZE")
  case  FROM                             extends KeyWordEnum("FROM")
  case  FSCK                             extends KeyWordEnum("FSCK")
  case  FULFILLMENT                      extends KeyWordEnum("FULFILLMENT")
  case  FULL                             extends KeyWordEnum("FULL")
  case  FULLTEXT                         extends KeyWordEnum("FULLTEXT")
  case  FUNCTION                         extends KeyWordEnum("FUNCTION")
  case  FUNCTIONS                        extends KeyWordEnum("FUNCTIONS")
  case  FUSION                           extends KeyWordEnum("FUSION")
  case  GENERAL                          extends KeyWordEnum("GENERAL")
  case  GENERATE                         extends KeyWordEnum("GENERATE")
  case  GENERATED                        extends KeyWordEnum("GENERATED")
  case  GEOGRAPHY                        extends KeyWordEnum("GEOGRAPHY")
  case  GET                              extends KeyWordEnum("GET")
  case  GIN                              extends KeyWordEnum("GIN")
  case  GIST                             extends KeyWordEnum("GIST")
  case  GLOBAL                           extends KeyWordEnum("GLOBAL")
  case  GRANT                            extends KeyWordEnum("GRANT")
  case  GRANTED                          extends KeyWordEnum("GRANTED")
  case  GRANTS                           extends KeyWordEnum("GRANTS")
  case  GRAPHVIZ                         extends KeyWordEnum("GRAPHVIZ")
  case  GROUP                            extends KeyWordEnum("GROUP")
  case  GROUPING                         extends KeyWordEnum("GROUPING")
  case  GROUPS                           extends KeyWordEnum("GROUPS")
  case  HASH                             extends KeyWordEnum("HASH")
  case  HAVING                           extends KeyWordEnum("HAVING")
  case  HEADER                           extends KeyWordEnum("HEADER")
  case  HEAP                             extends KeyWordEnum("HEAP")
  case  HIGH_PRIORITY                    extends KeyWordEnum("HIGH_PRIORITY")
  case  HISTORY                          extends KeyWordEnum("HISTORY")
  case  HIVEVAR                          extends KeyWordEnum("HIVEVAR")
  case  HOLD                             extends KeyWordEnum("HOLD")
  case  HOSTS                            extends KeyWordEnum("HOSTS")
  case  HOUR                             extends KeyWordEnum("HOUR")
  case  HOURS                            extends KeyWordEnum("HOURS")
  case  HUGEINT                          extends KeyWordEnum("HUGEINT")
  case  ICEBERG                          extends KeyWordEnum("ICEBERG")
  case  ID                               extends KeyWordEnum("ID")
  case  IDENTITY                         extends KeyWordEnum("IDENTITY")
  case  IDENTITY_INSERT                  extends KeyWordEnum("IDENTITY_INSERT")
  case  IF                               extends KeyWordEnum("IF")
  case  IGNORE                           extends KeyWordEnum("IGNORE")
  case  ILIKE                            extends KeyWordEnum("ILIKE")
  case  IMMEDIATE                        extends KeyWordEnum("IMMEDIATE")
  case  IMMUTABLE                        extends KeyWordEnum("IMMUTABLE")
  case  IMPORT                           extends KeyWordEnum("IMPORT")
  case  IMPORTED                         extends KeyWordEnum("IMPORTED")
  case  IN                               extends KeyWordEnum("IN")
  case  INCLUDE                          extends KeyWordEnum("INCLUDE")
  case  INCLUDE_NULL_VALUES              extends KeyWordEnum("INCLUDE_NULL_VALUES")
  case  INCREMENT                        extends KeyWordEnum("INCREMENT")
  case  INDEX                            extends KeyWordEnum("INDEX")
  case  INDICATOR                        extends KeyWordEnum("INDICATOR")
  case  INHERIT                          extends KeyWordEnum("INHERIT")
  case  INHERITS                         extends KeyWordEnum("INHERITS")
  case  INITIALLY                        extends KeyWordEnum("INITIALLY")
  case  INNER                            extends KeyWordEnum("INNER")
  case  INOUT                            extends KeyWordEnum("INOUT")
  case  INPATH                           extends KeyWordEnum("INPATH")
  case  INPLACE                          extends KeyWordEnum("INPLACE")
  case  INPUT                            extends KeyWordEnum("INPUT")
  case  INPUTFORMAT                      extends KeyWordEnum("INPUTFORMAT")
  case  INSENSITIVE                      extends KeyWordEnum("INSENSITIVE")
  case  INSERT                           extends KeyWordEnum("INSERT")
  case  INSERT_METHOD                    extends KeyWordEnum("INSERT_METHOD")
  case  INSTALL                          extends KeyWordEnum("INSTALL")
  case  INSTANT                          extends KeyWordEnum("INSTANT")
  case  INSTEAD                          extends KeyWordEnum("INSTEAD")
  case  INT                              extends KeyWordEnum("INT")
  case  INT128                           extends KeyWordEnum("INT128")
  case  INT16                            extends KeyWordEnum("INT16")
  case  INT2                             extends KeyWordEnum("INT2")
  case  INT256                           extends KeyWordEnum("INT256")
  case  INT32                            extends KeyWordEnum("INT32")
  case  INT4                             extends KeyWordEnum("INT4")
  case  INT64                            extends KeyWordEnum("INT64")
  case  INT8                             extends KeyWordEnum("INT8")
  case  INTEGER                          extends KeyWordEnum("INTEGER")
  case  INTEGRATION                      extends KeyWordEnum("INTEGRATION")
  case  INTERPOLATE                      extends KeyWordEnum("INTERPOLATE")
  case  INTERSECT                        extends KeyWordEnum("INTERSECT")
  case  INTERSECTION                     extends KeyWordEnum("INTERSECTION")
  case  INTERVAL                         extends KeyWordEnum("INTERVAL")
  case  INTO                             extends KeyWordEnum("INTO")
  case  INVOKER                          extends KeyWordEnum("INVOKER")
  case  IO                               extends KeyWordEnum("IO")
  case  IS                               extends KeyWordEnum("IS")
  case  ISODOW                           extends KeyWordEnum("ISODOW")
  case  ISOLATION                        extends KeyWordEnum("ISOLATION")
  case  ISOWEEK                          extends KeyWordEnum("ISOWEEK")
  case  ISOYEAR                          extends KeyWordEnum("ISOYEAR")
  case  ITEMS                            extends KeyWordEnum("ITEMS")
  case  JAR                              extends KeyWordEnum("JAR")
  case  JOIN                             extends KeyWordEnum("JOIN")
  case  JSON                             extends KeyWordEnum("JSON")
  case  JSONB                            extends KeyWordEnum("JSONB")
  case  JSONFILE                         extends KeyWordEnum("JSONFILE")
  case  JSON_TABLE                       extends KeyWordEnum("JSON_TABLE")
  case  JULIAN                           extends KeyWordEnum("JULIAN")
  case  KEY                              extends KeyWordEnum("KEY")
  case  KEYS                             extends KeyWordEnum("KEYS")
  case  KEY_BLOCK_SIZE                   extends KeyWordEnum("KEY_BLOCK_SIZE")
  case  KILL                             extends KeyWordEnum("KILL")
  case  LAG                              extends KeyWordEnum("LAG")
  case  LANGUAGE                         extends KeyWordEnum("LANGUAGE")
  case  LARGE                            extends KeyWordEnum("LARGE")
  case  LAST                             extends KeyWordEnum("LAST")
  case  LAST_VALUE                       extends KeyWordEnum("LAST_VALUE")
  case  LATERAL                          extends KeyWordEnum("LATERAL")
  case  LEAD                             extends KeyWordEnum("LEAD")
  case  LEADING                          extends KeyWordEnum("LEADING")
  case  LEFT                             extends KeyWordEnum("LEFT")
  case  LEVEL                            extends KeyWordEnum("LEVEL")
  case  LIKE                             extends KeyWordEnum("LIKE")
  case  LIKE_REGEX                       extends KeyWordEnum("LIKE_REGEX")
  case  LIMIT                            extends KeyWordEnum("LIMIT")
  case  LINE                             extends KeyWordEnum("LINE")
  case  LINES                            extends KeyWordEnum("LINES")
  case  LIST                             extends KeyWordEnum("LIST")
  case  LISTEN                           extends KeyWordEnum("LISTEN")
  case  LISTING                          extends KeyWordEnum("LISTING")
  case  LN                               extends KeyWordEnum("LN")
  case  LOAD                             extends KeyWordEnum("LOAD")
  case  LOCAL                            extends KeyWordEnum("LOCAL")
  case  LOCALTIME                        extends KeyWordEnum("LOCALTIME")
  case  LOCALTIMESTAMP                   extends KeyWordEnum("LOCALTIMESTAMP")
  case  LOCATION                         extends KeyWordEnum("LOCATION")
  case  LOCK                             extends KeyWordEnum("LOCK")
  case  LOCKED                           extends KeyWordEnum("LOCKED")
  case  LOG                              extends KeyWordEnum("LOG")
  case  LOGIN                            extends KeyWordEnum("LOGIN")
  case  LOGS                             extends KeyWordEnum("LOGS")
  case  LONGBLOB                         extends KeyWordEnum("LONGBLOB")
  case  LONGTEXT                         extends KeyWordEnum("LONGTEXT")
  case  LOWCARDINALITY                   extends KeyWordEnum("LOWCARDINALITY")
  case  LOWER                            extends KeyWordEnum("LOWER")
  case  LOW_PRIORITY                     extends KeyWordEnum("LOW_PRIORITY")
  case  LS                               extends KeyWordEnum("LS")
  case  LSEG                             extends KeyWordEnum("LSEG")
  case  MACRO                            extends KeyWordEnum("MACRO")
  case  MANAGE                           extends KeyWordEnum("MANAGE")
  case  MANAGED                          extends KeyWordEnum("MANAGED")
  case  MANAGEDLOCATION                  extends KeyWordEnum("MANAGEDLOCATION")
  case  MAP                              extends KeyWordEnum("MAP")
  case  MASKING                          extends KeyWordEnum("MASKING")
  case  MATCH                            extends KeyWordEnum("MATCH")
  case  MATCHED                          extends KeyWordEnum("MATCHED")
  case  MATCHES                          extends KeyWordEnum("MATCHES")
  case  MATCH_CONDITION                  extends KeyWordEnum("MATCH_CONDITION")
  case  MATCH_RECOGNIZE                  extends KeyWordEnum("MATCH_RECOGNIZE")
  case  MATERIALIZE                      extends KeyWordEnum("MATERIALIZE")
  case  MATERIALIZED                     extends KeyWordEnum("MATERIALIZED")
  case  MAX                              extends KeyWordEnum("MAX")
  case  MAXVALUE                         extends KeyWordEnum("MAXVALUE")
  case  MAX_DATA_EXTENSION_TIME_IN_DAYS  extends KeyWordEnum("MAX_DATA_EXTENSION_TIME_IN_DAYS")
  case  MAX_ROWS                         extends KeyWordEnum("MAX_ROWS")
  case  MEASURES                         extends KeyWordEnum("MEASURES")
  case  MEDIUMBLOB                       extends KeyWordEnum("MEDIUMBLOB")
  case  MEDIUMINT                        extends KeyWordEnum("MEDIUMINT")
  case  MEDIUMTEXT                       extends KeyWordEnum("MEDIUMTEXT")
  case  MEMBER                           extends KeyWordEnum("MEMBER")
  case  MERGE                            extends KeyWordEnum("MERGE")
  case  MESSAGE                          extends KeyWordEnum("MESSAGE")
  case  METADATA                         extends KeyWordEnum("METADATA")
  case  METHOD                           extends KeyWordEnum("METHOD")
  case  METRIC                           extends KeyWordEnum("METRIC")
  case  MICROSECOND                      extends KeyWordEnum("MICROSECOND")
  case  MICROSECONDS                     extends KeyWordEnum("MICROSECONDS")
  case  MILLENIUM                        extends KeyWordEnum("MILLENIUM")
  case  MILLENNIUM                       extends KeyWordEnum("MILLENNIUM")
  case  MILLISECOND                      extends KeyWordEnum("MILLISECOND")
  case  MILLISECONDS                     extends KeyWordEnum("MILLISECONDS")
  case  MIN                              extends KeyWordEnum("MIN")
  case  MINUS                            extends KeyWordEnum("MINUS")
  case  MINUTE                           extends KeyWordEnum("MINUTE")
  case  MINUTES                          extends KeyWordEnum("MINUTES")
  case  MINVALUE                         extends KeyWordEnum("MINVALUE")
  case  MIN_ROWS                         extends KeyWordEnum("MIN_ROWS")
  case  MOD                              extends KeyWordEnum("MOD")
  case  MODE                             extends KeyWordEnum("MODE")
  case  MODIFIES                         extends KeyWordEnum("MODIFIES")
  case  MODIFY                           extends KeyWordEnum("MODIFY")
  case  MODULE                           extends KeyWordEnum("MODULE")
  case  MONITOR                          extends KeyWordEnum("MONITOR")
  case  MONTH                            extends KeyWordEnum("MONTH")
  case  MONTHS                           extends KeyWordEnum("MONTHS")
  case  MSCK                             extends KeyWordEnum("MSCK")
  case  MULTISET                         extends KeyWordEnum("MULTISET")
  case  MUTATION                         extends KeyWordEnum("MUTATION")
  case  NAME                             extends KeyWordEnum("NAME")
  case  NAMES                            extends KeyWordEnum("NAMES")
  case  NANOSECOND                       extends KeyWordEnum("NANOSECOND")
  case  NANOSECONDS                      extends KeyWordEnum("NANOSECONDS")
  case  NATIONAL                         extends KeyWordEnum("NATIONAL")
  case  NATURAL                          extends KeyWordEnum("NATURAL")
  case  NCHAR                            extends KeyWordEnum("NCHAR")
  case  NCLOB                            extends KeyWordEnum("NCLOB")
  case  NESTED                           extends KeyWordEnum("NESTED")
  case  NETWORK                          extends KeyWordEnum("NETWORK")
  case  NEW                              extends KeyWordEnum("NEW")
  case  NEXT                             extends KeyWordEnum("NEXT")
  case  NFC                              extends KeyWordEnum("NFC")
  case  NFD                              extends KeyWordEnum("NFD")
  case  NFKC                             extends KeyWordEnum("NFKC")
  case  NFKD                             extends KeyWordEnum("NFKD")
  case  NO                               extends KeyWordEnum("NO")
  case  NOBYPASSRLS                      extends KeyWordEnum("NOBYPASSRLS")
  case  NOCREATEDB                       extends KeyWordEnum("NOCREATEDB")
  case  NOCREATEROLE                     extends KeyWordEnum("NOCREATEROLE")
  case  NOINHERIT                        extends KeyWordEnum("NOINHERIT")
  case  NOLOGIN                          extends KeyWordEnum("NOLOGIN")
  case  NONE                             extends KeyWordEnum("NONE")
  case  NOORDER                          extends KeyWordEnum("NOORDER")
  case  NOREPLICATION                    extends KeyWordEnum("NOREPLICATION")
  case  NORMALIZE                        extends KeyWordEnum("NORMALIZE")
  case  NORMALIZED                       extends KeyWordEnum("NORMALIZED")
  case  NOSCAN                           extends KeyWordEnum("NOSCAN")
  case  NOSUPERUSER                      extends KeyWordEnum("NOSUPERUSER")
  case  NOT                              extends KeyWordEnum("NOT")
  case  NOTHING                          extends KeyWordEnum("NOTHING")
  case  NOTIFY                           extends KeyWordEnum("NOTIFY")
  case  NOWAIT                           extends KeyWordEnum("NOWAIT")
  case  NO_WRITE_TO_BINLOG               extends KeyWordEnum("NO_WRITE_TO_BINLOG")
  case  NTH_VALUE                        extends KeyWordEnum("NTH_VALUE")
  case  NTILE                            extends KeyWordEnum("NTILE")
  case  NULL                             extends KeyWordEnum("NULL")
  case  NULLABLE                         extends KeyWordEnum("NULLABLE")
  case  NULLIF                           extends KeyWordEnum("NULLIF")
  case  NULLS                            extends KeyWordEnum("NULLS")
  case  NUMERIC                          extends KeyWordEnum("NUMERIC")
  case  NVARCHAR                         extends KeyWordEnum("NVARCHAR")
  case  OBJECT                           extends KeyWordEnum("OBJECT")
  case  OBJECTS                          extends KeyWordEnum("OBJECTS")
  case  OCCURRENCES_REGEX                extends KeyWordEnum("OCCURRENCES_REGEX")
  case  OCTETS                           extends KeyWordEnum("OCTETS")
  case  OCTET_LENGTH                     extends KeyWordEnum("OCTET_LENGTH")
  case  OF                               extends KeyWordEnum("OF")
  case  OFF                              extends KeyWordEnum("OFF")
  case  OFFSET                           extends KeyWordEnum("OFFSET")
  case  OFFSETS                          extends KeyWordEnum("OFFSETS")
  case  OLD                              extends KeyWordEnum("OLD")
  case  OMIT                             extends KeyWordEnum("OMIT")
  case  ON                               extends KeyWordEnum("ON")
  case  ONE                              extends KeyWordEnum("ONE")
  case  ONLY                             extends KeyWordEnum("ONLY")
  case  OPEN                             extends KeyWordEnum("OPEN")
  case  OPENJSON                         extends KeyWordEnum("OPENJSON")
  case  OPERATE                          extends KeyWordEnum("OPERATE")
  case  OPERATOR                         extends KeyWordEnum("OPERATOR")
  case  OPTIMIZATION                     extends KeyWordEnum("OPTIMIZATION")
  case  OPTIMIZE                         extends KeyWordEnum("OPTIMIZE")
  case  OPTIMIZED                        extends KeyWordEnum("OPTIMIZED")
  case  OPTIMIZER_COSTS                  extends KeyWordEnum("OPTIMIZER_COSTS")
  case  OPTION                           extends KeyWordEnum("OPTION")
  case  OPTIONS                          extends KeyWordEnum("OPTIONS")
  case  OR                               extends KeyWordEnum("OR")
  case  ORC                              extends KeyWordEnum("ORC")
  case  ORDER                            extends KeyWordEnum("ORDER")
  case  ORDINALITY                       extends KeyWordEnum("ORDINALITY")
  case  ORGANIZATION                     extends KeyWordEnum("ORGANIZATION")
  case  OUT                              extends KeyWordEnum("OUT")
  case  OUTER                            extends KeyWordEnum("OUTER")
  case  OUTPUT                           extends KeyWordEnum("OUTPUT")
  case  OUTPUTFORMAT                     extends KeyWordEnum("OUTPUTFORMAT")
  case  OVER                             extends KeyWordEnum("OVER")
  case  OVERFLOW                         extends KeyWordEnum("OVERFLOW")
  case  OVERLAPS                         extends KeyWordEnum("OVERLAPS")
  case  OVERLAY                          extends KeyWordEnum("OVERLAY")
  case  OVERRIDE                         extends KeyWordEnum("OVERRIDE")
  case  OVERWRITE                        extends KeyWordEnum("OVERWRITE")
  case  OWNED                            extends KeyWordEnum("OWNED")
  case  OWNER                            extends KeyWordEnum("OWNER")
  case  OWNERSHIP                        extends KeyWordEnum("OWNERSHIP")
  case  PACKAGE                          extends KeyWordEnum("PACKAGE")
  case  PACKAGES                         extends KeyWordEnum("PACKAGES")
  case  PACK_KEYS                        extends KeyWordEnum("PACK_KEYS")
  case  PARALLEL                         extends KeyWordEnum("PARALLEL")
  case  PARAMETER                        extends KeyWordEnum("PARAMETER")
  case  PARQUET                          extends KeyWordEnum("PARQUET")
  case  PART                             extends KeyWordEnum("PART")
  case  PARTITION                        extends KeyWordEnum("PARTITION")
  case  PARTITIONED                      extends KeyWordEnum("PARTITIONED")
  case  PARTITIONS                       extends KeyWordEnum("PARTITIONS")
  case  PASSING                          extends KeyWordEnum("PASSING")
  case  PASSWORD                         extends KeyWordEnum("PASSWORD")
  case  PAST                             extends KeyWordEnum("PAST")
  case  PATH                             extends KeyWordEnum("PATH")
  case  PATTERN                          extends KeyWordEnum("PATTERN")
  case  PER                              extends KeyWordEnum("PER")
  case  PERCENT                          extends KeyWordEnum("PERCENT")
  case  PERCENTILE_CONT                  extends KeyWordEnum("PERCENTILE_CONT")
  case  PERCENTILE_DISC                  extends KeyWordEnum("PERCENTILE_DISC")
  case  PERCENT_RANK                     extends KeyWordEnum("PERCENT_RANK")
  case  PERIOD                           extends KeyWordEnum("PERIOD")
  case  PERMISSIVE                       extends KeyWordEnum("PERMISSIVE")
  case  PERSISTENT                       extends KeyWordEnum("PERSISTENT")
  case  PIVOT                            extends KeyWordEnum("PIVOT")
  case  PLACING                          extends KeyWordEnum("PLACING")
  case  PLAN                             extends KeyWordEnum("PLAN")
  case  PLANS                            extends KeyWordEnum("PLANS")
  case  POINT                            extends KeyWordEnum("POINT")
  case  POLICY                           extends KeyWordEnum("POLICY")
  case  POLYGON                          extends KeyWordEnum("POLYGON")
  case  POOL                             extends KeyWordEnum("POOL")
  case  PORTION                          extends KeyWordEnum("PORTION")
  case  POSITION                         extends KeyWordEnum("POSITION")
  case  POSITION_REGEX                   extends KeyWordEnum("POSITION_REGEX")
  case  POWER                            extends KeyWordEnum("POWER")
  case  PRAGMA                           extends KeyWordEnum("PRAGMA")
  case  PRECEDES                         extends KeyWordEnum("PRECEDES")
  case  PRECEDING                        extends KeyWordEnum("PRECEDING")
  case  PRECISION                        extends KeyWordEnum("PRECISION")
  case  PREPARE                          extends KeyWordEnum("PREPARE")
  case  PRESERVE                         extends KeyWordEnum("PRESERVE")
  case  PREWHERE                         extends KeyWordEnum("PREWHERE")
  case  PRIMARY                          extends KeyWordEnum("PRIMARY")
  case  PRINT                            extends KeyWordEnum("PRINT")
  case  PRIOR                            extends KeyWordEnum("PRIOR")
  case  PRIVILEGES                       extends KeyWordEnum("PRIVILEGES")
  case  PROCEDURE                        extends KeyWordEnum("PROCEDURE")
  case  PROFILE                          extends KeyWordEnum("PROFILE")
  case  PROGRAM                          extends KeyWordEnum("PROGRAM")
  case  PROJECTION                       extends KeyWordEnum("PROJECTION")
  case  PUBLIC                           extends KeyWordEnum("PUBLIC")
  case  PURCHASE                         extends KeyWordEnum("PURCHASE")
  case  PURGE                            extends KeyWordEnum("PURGE")
  case  QUALIFY                          extends KeyWordEnum("QUALIFY")
  case  QUARTER                          extends KeyWordEnum("QUARTER")
  case  QUERY                            extends KeyWordEnum("QUERY")
  case  QUOTE                            extends KeyWordEnum("QUOTE")
  case  RAISE                            extends KeyWordEnum("RAISE")
  case  RAISERROR                        extends KeyWordEnum("RAISERROR")
  case  RANGE                            extends KeyWordEnum("RANGE")
  case  RANK                             extends KeyWordEnum("RANK")
  case  RAW                              extends KeyWordEnum("RAW")
  case  RCFILE                           extends KeyWordEnum("RCFILE")
  case  READ                             extends KeyWordEnum("READ")
  case  READS                            extends KeyWordEnum("READS")
  case  READ_ONLY                        extends KeyWordEnum("READ_ONLY")
  case  REAL                             extends KeyWordEnum("REAL")
  case  RECLUSTER                        extends KeyWordEnum("RECLUSTER")
  case  RECURSIVE                        extends KeyWordEnum("RECURSIVE")
  case  REF                              extends KeyWordEnum("REF")
  case  REFERENCES                       extends KeyWordEnum("REFERENCES")
  case  REFERENCING                      extends KeyWordEnum("REFERENCING")
  case  REGCLASS                         extends KeyWordEnum("REGCLASS")
  case  REGEXP                           extends KeyWordEnum("REGEXP")
  case  REGR_AVGX                        extends KeyWordEnum("REGR_AVGX")
  case  REGR_AVGY                        extends KeyWordEnum("REGR_AVGY")
  case  REGR_COUNT                       extends KeyWordEnum("REGR_COUNT")
  case  REGR_INTERCEPT                   extends KeyWordEnum("REGR_INTERCEPT")
  case  REGR_R2                          extends KeyWordEnum("REGR_R2")
  case  REGR_SLOPE                       extends KeyWordEnum("REGR_SLOPE")
  case  REGR_SXX                         extends KeyWordEnum("REGR_SXX")
  case  REGR_SXY                         extends KeyWordEnum("REGR_SXY")
  case  REGR_SYY                         extends KeyWordEnum("REGR_SYY")
  case  RELATIVE                         extends KeyWordEnum("RELATIVE")
  case  RELAY                            extends KeyWordEnum("RELAY")
  case  RELEASE                          extends KeyWordEnum("RELEASE")
  case  RELEASES                         extends KeyWordEnum("RELEASES")
  case  REMOTE                           extends KeyWordEnum("REMOTE")
  case  REMOVE                           extends KeyWordEnum("REMOVE")
  case  RENAME                           extends KeyWordEnum("RENAME")
  case  REORG                            extends KeyWordEnum("REORG")
  case  REPAIR                           extends KeyWordEnum("REPAIR")
  case  REPEATABLE                       extends KeyWordEnum("REPEATABLE")
  case  REPLACE                          extends KeyWordEnum("REPLACE")
  case  REPLICA                          extends KeyWordEnum("REPLICA")
  case  REPLICATE                        extends KeyWordEnum("REPLICATE")
  case  REPLICATION                      extends KeyWordEnum("REPLICATION")
  case  RESET                            extends KeyWordEnum("RESET")
  case  RESOLVE                          extends KeyWordEnum("RESOLVE")
  case  RESOURCE                         extends KeyWordEnum("RESOURCE")
  case  RESPECT                          extends KeyWordEnum("RESPECT")
  case  RESTART                          extends KeyWordEnum("RESTART")
  case  RESTRICT                         extends KeyWordEnum("RESTRICT")
  case  RESTRICTED                       extends KeyWordEnum("RESTRICTED")
  case  RESTRICTIONS                     extends KeyWordEnum("RESTRICTIONS")
  case  RESTRICTIVE                      extends KeyWordEnum("RESTRICTIVE")
  case  RESULT                           extends KeyWordEnum("RESULT")
  case  RESULTSET                        extends KeyWordEnum("RESULTSET")
  case  RESUME                           extends KeyWordEnum("RESUME")
  case  RETAIN                           extends KeyWordEnum("RETAIN")
  case  RETURN                           extends KeyWordEnum("RETURN")
  case  RETURNING                        extends KeyWordEnum("RETURNING")
  case  RETURNS                          extends KeyWordEnum("RETURNS")
  case  REVOKE                           extends KeyWordEnum("REVOKE")
  case  RIGHT                            extends KeyWordEnum("RIGHT")
  case  RLIKE                            extends KeyWordEnum("RLIKE")
  case  RM                               extends KeyWordEnum("RM")
  case  ROLE                             extends KeyWordEnum("ROLE")
  case  ROLES                            extends KeyWordEnum("ROLES")
  case  ROLLBACK                         extends KeyWordEnum("ROLLBACK")
  case  ROLLUP                           extends KeyWordEnum("ROLLUP")
  case  ROOT                             extends KeyWordEnum("ROOT")
  case  ROW                              extends KeyWordEnum("ROW")
  case  ROWID                            extends KeyWordEnum("ROWID")
  case  ROWS                             extends KeyWordEnum("ROWS")
  case  ROW_FORMAT                       extends KeyWordEnum("ROW_FORMAT")
  case  ROW_NUMBER                       extends KeyWordEnum("ROW_NUMBER")
  case  RULE                             extends KeyWordEnum("RULE")
  case  RUN                              extends KeyWordEnum("RUN")
  case  SAFE                             extends KeyWordEnum("SAFE")
  case  SAFE_CAST                        extends KeyWordEnum("SAFE_CAST")
  case  SAMPLE                           extends KeyWordEnum("SAMPLE")
  case  SAVEPOINT                        extends KeyWordEnum("SAVEPOINT")
  case  SCHEMA                           extends KeyWordEnum("SCHEMA")
  case  SCHEMAS                          extends KeyWordEnum("SCHEMAS")
  case  SCOPE                            extends KeyWordEnum("SCOPE")
  case  SCROLL                           extends KeyWordEnum("SCROLL")
  case  SEARCH                           extends KeyWordEnum("SEARCH")
  case  SECOND                           extends KeyWordEnum("SECOND")
  case  SECONDARY                        extends KeyWordEnum("SECONDARY")
  case  SECONDARY_ENGINE_ATTRIBUTE       extends KeyWordEnum("SECONDARY_ENGINE_ATTRIBUTE")
  case  SECONDS                          extends KeyWordEnum("SECONDS")
  case  SECRET                           extends KeyWordEnum("SECRET")
  case  SECURITY                         extends KeyWordEnum("SECURITY")
  case  SEED                             extends KeyWordEnum("SEED")
  case  SELECT                           extends KeyWordEnum("SELECT")
  case  SEMI                             extends KeyWordEnum("SEMI")
  case  SENSITIVE                        extends KeyWordEnum("SENSITIVE")
  case  SEPARATOR                        extends KeyWordEnum("SEPARATOR")
  case  SEQUENCE                         extends KeyWordEnum("SEQUENCE")
  case  SEQUENCEFILE                     extends KeyWordEnum("SEQUENCEFILE")
  case  SEQUENCES                        extends KeyWordEnum("SEQUENCES")
  case  SERDE                            extends KeyWordEnum("SERDE")
  case  SERDEPROPERTIES                  extends KeyWordEnum("SERDEPROPERTIES")
  case  SERIALIZABLE                     extends KeyWordEnum("SERIALIZABLE")
  case  SERVICE                          extends KeyWordEnum("SERVICE")
  case  SESSION                          extends KeyWordEnum("SESSION")
  case  SESSION_USER                     extends KeyWordEnum("SESSION_USER")
  case  SET                              extends KeyWordEnum("SET")
  case  SETERROR                         extends KeyWordEnum("SETERROR")
  case  SETS                             extends KeyWordEnum("SETS")
  case  SETTINGS                         extends KeyWordEnum("SETTINGS")
  case  SHARE                            extends KeyWordEnum("SHARE")
  case  SHARED                           extends KeyWordEnum("SHARED")
  case  SHARING                          extends KeyWordEnum("SHARING")
  case  SHOW                             extends KeyWordEnum("SHOW")
  case  SIGNED                           extends KeyWordEnum("SIGNED")
  case  SIMILAR                          extends KeyWordEnum("SIMILAR")
  case  SKIP                             extends KeyWordEnum("SKIP")
  case  SLOW                             extends KeyWordEnum("SLOW")
  case  SMALLINT                         extends KeyWordEnum("SMALLINT")
  case  SNAPSHOT                         extends KeyWordEnum("SNAPSHOT")
  case  SOME                             extends KeyWordEnum("SOME")
  case  SORT                             extends KeyWordEnum("SORT")
  case  SORTED                           extends KeyWordEnum("SORTED")
  case  SOURCE                           extends KeyWordEnum("SOURCE")
  case  SPATIAL                          extends KeyWordEnum("SPATIAL")
  case  SPECIFIC                         extends KeyWordEnum("SPECIFIC")
  case  SPECIFICTYPE                     extends KeyWordEnum("SPECIFICTYPE")
  case  SPGIST                           extends KeyWordEnum("SPGIST")
  case  SQL                              extends KeyWordEnum("SQL")
  case  SQLEXCEPTION                     extends KeyWordEnum("SQLEXCEPTION")
  case  SQLSTATE                         extends KeyWordEnum("SQLSTATE")
  case  SQLWARNING                       extends KeyWordEnum("SQLWARNING")
  case  SQRT                             extends KeyWordEnum("SQRT")
  case  SRID                             extends KeyWordEnum("SRID")
  case  STABLE                           extends KeyWordEnum("STABLE")
  case  STAGE                            extends KeyWordEnum("STAGE")
  case  START                            extends KeyWordEnum("START")
  case  STARTS                           extends KeyWordEnum("STARTS")
  case  STATEMENT                        extends KeyWordEnum("STATEMENT")
  case  STATIC                           extends KeyWordEnum("STATIC")
  case  STATISTICS                       extends KeyWordEnum("STATISTICS")
  case  STATS_AUTO_RECALC                extends KeyWordEnum("STATS_AUTO_RECALC")
  case  STATS_PERSISTENT                 extends KeyWordEnum("STATS_PERSISTENT")
  case  STATS_SAMPLE_PAGES               extends KeyWordEnum("STATS_SAMPLE_PAGES")
  case  STATUS                           extends KeyWordEnum("STATUS")
  case  STDDEV_POP                       extends KeyWordEnum("STDDEV_POP")
  case  STDDEV_SAMP                      extends KeyWordEnum("STDDEV_SAMP")
  case  STDIN                            extends KeyWordEnum("STDIN")
  case  STDOUT                           extends KeyWordEnum("STDOUT")
  case  STEP                             extends KeyWordEnum("STEP")
  case  STORAGE                          extends KeyWordEnum("STORAGE")
  case  STORAGE_INTEGRATION              extends KeyWordEnum("STORAGE_INTEGRATION")
  case  STORAGE_SERIALIZATION_POLICY     extends KeyWordEnum("STORAGE_SERIALIZATION_POLICY")
  case  STORED                           extends KeyWordEnum("STORED")
  case  STRAIGHT_JOIN                    extends KeyWordEnum("STRAIGHT_JOIN")
  case  STRICT                           extends KeyWordEnum("STRICT")
  case  STRING                           extends KeyWordEnum("STRING")
  case  STRUCT                           extends KeyWordEnum("STRUCT")
  case  SUBMULTISET                      extends KeyWordEnum("SUBMULTISET")
  case  SUBSTR                           extends KeyWordEnum("SUBSTR")
  case  SUBSTRING                        extends KeyWordEnum("SUBSTRING")
  case  SUBSTRING_REGEX                  extends KeyWordEnum("SUBSTRING_REGEX")
  case  SUCCEEDS                         extends KeyWordEnum("SUCCEEDS")
  case  SUM                              extends KeyWordEnum("SUM")
  case  SUPER                            extends KeyWordEnum("SUPER")
  case  SUPERUSER                        extends KeyWordEnum("SUPERUSER")
  case  SUPPORT                          extends KeyWordEnum("SUPPORT")
  case  SUSPEND                          extends KeyWordEnum("SUSPEND")
  case  SWAP                             extends KeyWordEnum("SWAP")
  case  SYMMETRIC                        extends KeyWordEnum("SYMMETRIC")
  case  SYNC                             extends KeyWordEnum("SYNC")
  case  SYSTEM                           extends KeyWordEnum("SYSTEM")
  case  SYSTEM_TIME                      extends KeyWordEnum("SYSTEM_TIME")
  case  SYSTEM_USER                      extends KeyWordEnum("SYSTEM_USER")
  case  TABLE                            extends KeyWordEnum("TABLE")
  case  TABLES                           extends KeyWordEnum("TABLES")
  case  TABLESAMPLE                      extends KeyWordEnum("TABLESAMPLE")
  case  TABLESPACE                       extends KeyWordEnum("TABLESPACE")
  case  TAG                              extends KeyWordEnum("TAG")
  case  TARGET                           extends KeyWordEnum("TARGET")
  case  TASK                             extends KeyWordEnum("TASK")
  case  TBLPROPERTIES                    extends KeyWordEnum("TBLPROPERTIES")
  case  TEMP                             extends KeyWordEnum("TEMP")
  case  TEMPORARY                        extends KeyWordEnum("TEMPORARY")
  case  TEMPTABLE                        extends KeyWordEnum("TEMPTABLE")
  case  TERMINATED                       extends KeyWordEnum("TERMINATED")
  case  TERSE                            extends KeyWordEnum("TERSE")
  case  TEXT                             extends KeyWordEnum("TEXT")
  case  TEXTFILE                         extends KeyWordEnum("TEXTFILE")
  case  THEN                             extends KeyWordEnum("THEN")
  case  TIES                             extends KeyWordEnum("TIES")
  case  TIME                             extends KeyWordEnum("TIME")
  case  TIMESTAMP                        extends KeyWordEnum("TIMESTAMP")
  case  TIMESTAMPTZ                      extends KeyWordEnum("TIMESTAMPTZ")
  case  TIMESTAMP_NTZ                    extends KeyWordEnum("TIMESTAMP_NTZ")
  case  TIMETZ                           extends KeyWordEnum("TIMETZ")
  case  TIMEZONE                         extends KeyWordEnum("TIMEZONE")
  case  TIMEZONE_ABBR                    extends KeyWordEnum("TIMEZONE_ABBR")
  case  TIMEZONE_HOUR                    extends KeyWordEnum("TIMEZONE_HOUR")
  case  TIMEZONE_MINUTE                  extends KeyWordEnum("TIMEZONE_MINUTE")
  case  TIMEZONE_REGION                  extends KeyWordEnum("TIMEZONE_REGION")
  case  TINYBLOB                         extends KeyWordEnum("TINYBLOB")
  case  TINYINT                          extends KeyWordEnum("TINYINT")
  case  TINYTEXT                         extends KeyWordEnum("TINYTEXT")
  case  TO                               extends KeyWordEnum("TO")
  case  TOP                              extends KeyWordEnum("TOP")
  case  TOTALS                           extends KeyWordEnum("TOTALS")
  case  TRACE                            extends KeyWordEnum("TRACE")
  case  TRAILING                         extends KeyWordEnum("TRAILING")
  case  TRANSACTION                      extends KeyWordEnum("TRANSACTION")
  case  TRANSIENT                        extends KeyWordEnum("TRANSIENT")
  case  TRANSLATE                        extends KeyWordEnum("TRANSLATE")
  case  TRANSLATE_REGEX                  extends KeyWordEnum("TRANSLATE_REGEX")
  case  TRANSLATION                      extends KeyWordEnum("TRANSLATION")
  case  TREAT                            extends KeyWordEnum("TREAT")
  case  TRIGGER                          extends KeyWordEnum("TRIGGER")
  case  TRIM                             extends KeyWordEnum("TRIM")
  case  TRIM_ARRAY                       extends KeyWordEnum("TRIM_ARRAY")
  case  TRUE                             extends KeyWordEnum("TRUE")
  case  TRUNCATE                         extends KeyWordEnum("TRUNCATE")
  case  TRY                              extends KeyWordEnum("TRY")
  case  TRY_CAST                         extends KeyWordEnum("TRY_CAST")
  case  TRY_CONVERT                      extends KeyWordEnum("TRY_CONVERT")
  case  TUPLE                            extends KeyWordEnum("TUPLE")
  case  TYPE                             extends KeyWordEnum("TYPE")
  case  UBIGINT                          extends KeyWordEnum("UBIGINT")
  case  UESCAPE                          extends KeyWordEnum("UESCAPE")
  case  UHUGEINT                         extends KeyWordEnum("UHUGEINT")
  case  UINT128                          extends KeyWordEnum("UINT128")
  case  UINT16                           extends KeyWordEnum("UINT16")
  case  UINT256                          extends KeyWordEnum("UINT256")
  case  UINT32                           extends KeyWordEnum("UINT32")
  case  UINT64                           extends KeyWordEnum("UINT64")
  case  UINT8                            extends KeyWordEnum("UINT8")
  case  UNBOUNDED                        extends KeyWordEnum("UNBOUNDED")
  case  UNCACHE                          extends KeyWordEnum("UNCACHE")
  case  UNCOMMITTED                      extends KeyWordEnum("UNCOMMITTED")
  case  UNDEFINED                        extends KeyWordEnum("UNDEFINED")
  case  UNFREEZE                         extends KeyWordEnum("UNFREEZE")
  case  UNION                            extends KeyWordEnum("UNION")
  case  UNIQUE                           extends KeyWordEnum("UNIQUE")
  case  UNKNOWN                          extends KeyWordEnum("UNKNOWN")
  case  UNLISTEN                         extends KeyWordEnum("UNLISTEN")
  case  UNLOAD                           extends KeyWordEnum("UNLOAD")
  case  UNLOCK                           extends KeyWordEnum("UNLOCK")
  case  UNLOGGED                         extends KeyWordEnum("UNLOGGED")
  case  UNMATCHED                        extends KeyWordEnum("UNMATCHED")
  case  UNNEST                           extends KeyWordEnum("UNNEST")
  case  UNPIVOT                          extends KeyWordEnum("UNPIVOT")
  case  UNSAFE                           extends KeyWordEnum("UNSAFE")
  case  UNSET                            extends KeyWordEnum("UNSET")
  case  UNSIGNED                         extends KeyWordEnum("UNSIGNED")
  case  UNTIL                            extends KeyWordEnum("UNTIL")
  case  UPDATE                           extends KeyWordEnum("UPDATE")
  case  UPPER                            extends KeyWordEnum("UPPER")
  case  URL                              extends KeyWordEnum("URL")
  case  USAGE                            extends KeyWordEnum("USAGE")
  case  USE                              extends KeyWordEnum("USE")
  case  USER                             extends KeyWordEnum("USER")
  case  USER_RESOURCES                   extends KeyWordEnum("USER_RESOURCES")
  case  USING                            extends KeyWordEnum("USING")
  case  USMALLINT                        extends KeyWordEnum("USMALLINT")
  case  UTINYINT                         extends KeyWordEnum("UTINYINT")
  case  UUID                             extends KeyWordEnum("UUID")
  case  VACUUM                           extends KeyWordEnum("VACUUM")
  case  VALID                            extends KeyWordEnum("VALID")
  case  VALIDATION_MODE                  extends KeyWordEnum("VALIDATION_MODE")
  case  VALUE                            extends KeyWordEnum("VALUE")
  case  VALUES                           extends KeyWordEnum("VALUES")
  case  VALUE_OF                         extends KeyWordEnum("VALUE_OF")
  case  VARBINARY                        extends KeyWordEnum("VARBINARY")
  case  VARBIT                           extends KeyWordEnum("VARBIT")
  case  VARCHAR                          extends KeyWordEnum("VARCHAR")
  case  VARIABLES                        extends KeyWordEnum("VARIABLES")
  case  VARYING                          extends KeyWordEnum("VARYING")
  case  VAR_POP                          extends KeyWordEnum("VAR_POP")
  case  VAR_SAMP                         extends KeyWordEnum("VAR_SAMP")
  case  VERBOSE                          extends KeyWordEnum("VERBOSE")
  case  VERSION                          extends KeyWordEnum("VERSION")
  case  VERSIONING                       extends KeyWordEnum("VERSIONING")
  case  VERSIONS                         extends KeyWordEnum("VERSIONS")
  case  VIEW                             extends KeyWordEnum("VIEW")
  case  VIEWS                            extends KeyWordEnum("VIEWS")
  case  VIRTUAL                          extends KeyWordEnum("VIRTUAL")
  case  VOLATILE                         extends KeyWordEnum("VOLATILE")
  case  VOLUME                           extends KeyWordEnum("VOLUME")
  case  WAREHOUSE                        extends KeyWordEnum("WAREHOUSE")
  case  WAREHOUSES                       extends KeyWordEnum("WAREHOUSES")
  case  WEEK                             extends KeyWordEnum("WEEK")
  case  WEEKS                            extends KeyWordEnum("WEEKS")
  case  WHEN                             extends KeyWordEnum("WHEN")
  case  WHENEVER                         extends KeyWordEnum("WHENEVER")
  case  WHERE                            extends KeyWordEnum("WHERE")
  case  WHILE                            extends KeyWordEnum("WHILE")
  case  WIDTH_BUCKET                     extends KeyWordEnum("WIDTH_BUCKET")
  case  WINDOW                           extends KeyWordEnum("WINDOW")
  case  WITH                             extends KeyWordEnum("WITH")
  case  WITHIN                           extends KeyWordEnum("WITHIN")
  case  WITHOUT                          extends KeyWordEnum("WITHOUT")
  case  WITHOUT_ARRAY_WRAPPER            extends KeyWordEnum("WITHOUT_ARRAY_WRAPPER")
  case  WORK                             extends KeyWordEnum("WORK")
  case  WRITE                            extends KeyWordEnum("WRITE")
  case  XML                              extends KeyWordEnum("XML")
  case  XMLNAMESPACES                    extends KeyWordEnum("XMLNAMESPACES")
  case  XMLTABLE                         extends KeyWordEnum("XMLTABLE")
  case  XOR                              extends KeyWordEnum("XOR")
  case  YEAR                             extends KeyWordEnum("YEAR")
  case  YEARS                            extends KeyWordEnum("YEARS")
  case  ZONE                             extends KeyWordEnum("ZONE")
  case  ZORDER                           extends KeyWordEnum("ZORDER")

object KeyWordEnum {

  def fromName(name: String): Option[KeyWordEnum] =
      values.find(_.toString == name.toUpperCase())

  /** These keywords can't be used as a table alias, so that `FROM table_name alias` can be parsed
    * unambiguously without looking ahead.
    */
  val RESERVED_FOR_TABLE_ALIAS: Set[KeyWordEnum] = Set(
    // Reserved as both a table and a column alias:
    WITH,
    EXPLAIN,
    ANALYZE,
    SELECT,
    WHERE,
    GROUP,
    SORT,
    HAVING,
    ORDER,
    PIVOT,
    UNPIVOT,
    TOP,
    LATERAL,
    VIEW,
    LIMIT,
    OFFSET,
    FETCH,
    UNION,
    EXCEPT,
    INTERSECT,
    MINUS,
    // Reserved only as a table alias in the `FROM`/`JOIN` clauses:
    ON,
    JOIN,
    INNER,
    CROSS,
    FULL,
    LEFT,
    RIGHT,
    NATURAL,
    USING,
    CLUSTER,
    DISTRIBUTE,
    GLOBAL,
    ANTI,
    SEMI,
    RETURNING,
    ASOF,
    MATCH_CONDITION,
    // for MSSQL-specific OUTER APPLY (seems reserved in most dialects)
    OUTER,
    SET,
    QUALIFY,
    WINDOW,
    END,
    FOR,
    // for MYSQL PARTITION SELECTION
    PARTITION,
    // for Clickhouse PREWHERE
    PREWHERE,
    SETTINGS,
    FORMAT,
    // for Snowflake START WITH .. CONNECT BY
    START,
    CONNECT,
    // Reserved for snowflake MATCH_RECOGNIZE
    MATCH_RECOGNIZE,
    // Reserved for Snowflake table sample
    SAMPLE,
    TABLESAMPLE,
    FROM,
    OPEN
  )

  /** Can't be used as a column alias. so that `SELECT <expr> alias`can be parsed unambiguously
    * without looking ahead.
    */
  val RESERVED_FOR_COLUMN_ALIAS: Set[KeyWordEnum] = Set(
    // Reserved as both a table and a column alias:
    WITH,
    EXPLAIN,
    ANALYZE,
    SELECT,
    WHERE,
    GROUP,
    SORT,
    HAVING,
    ORDER,
    TOP,
    LATERAL,
    VIEW,
    LIMIT,
    OFFSET,
    FETCH,
    UNION,
    EXCEPT,
    INTERSECT,
    MINUS,
    CLUSTER,
    DISTRIBUTE,
    RETURNING,
    // Reserved only as a column alias in the `SELECT` clause
    FROM,
    INTO,
    END
  )

  /** Global list of reserved keywords allowed after FROM. Parser should call
    * Dialect::get_reserved_keyword_after_from to allow for each dialect to customize the list.
    */
  val RESERVED_FOR_TABLE_FACTOR: Set[KeyWordEnum] = Set(
    INTO,
    LIMIT,
    HAVING,
    WHERE
  )

  /** Global list of reserved keywords that cannot be parsed as identifiers without special handling
    * like quoting. Parser should call `Dialect::is_reserved_for_identifier` to allow for each
    * dialect to customize the list.
    */
  val RESERVED_FOR_IDENTIFIER: Set[KeyWordEnum] = Set(
    EXISTS,
    INTERVAL,
    STRUCT,
    TRIM
  )
}
